#include<iostream.h>
#include<conio.h>
class std
{
  public:
	int st_id;
	int st_age;
	int st_name;
	student input(int n, int a, string s);
	{
	  student jay;
	  jay.st_id=n;
	  jay.st_age=a;
	  jay.st_name=b;
	  return jay;
	}
	void disp(student jay)
	{
	  cout<<"ROLL NO:"<<jay.st_rno<<endl;
	  cout<<"AGE:"<<jay.st_age<<endl;
	  cout<<"NAME:"<<jay.st_name<<endl;
	}

};
int main()
{
clrscr();
std H;
H=s.input(10,17,JAY)
s.disp(s);
getch();
return 0;
}